server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 10.120.23.11:1111 #nginx反向代理Nacos集群

management:
  endpoints:
    web:
      exposure:
        include: '*'